//! Build-time wordlist → FST conversion.
//!
//! The wordlist text files committed under `data/wordlists/` are the
//! human-readable source of truth. At build time we sort + dedupe
//! them and write a [BurntSushi FST](https://docs.rs/fst) `Set` blob
//! per layout into `OUT_DIR`. The runtime then `include_bytes!` them
//! and wraps the slice in `fst::Set::new(&'static [u8])` — O(len)
//! exact lookup with no per-word heap allocation.
//!
//! Why not commit the FST blobs directly: txt diffs are reviewable in
//! PRs, and FST encoding can change subtly across `fst` crate
//! versions. Generating at build time keeps the repo source-only.

// Build scripts are explicitly allowed to use unwrap/expect per the
// project's CLAUDE.md style — a panic here is an honest "build is
// broken" signal, not a runtime hazard.
#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::fs::File;
use std::io::{BufRead, BufReader, BufWriter, Write};
use std::path::PathBuf;

use fst::SetBuilder;

/// (`<layout-id-as-file-stem>`, expected layout BCP-47 tag for the
/// "did we wire it up?" diagnostic — only used in the build log).
const LAYOUTS: &[(&str, &str)] = &[("en_us", "en-US"), ("uk_ua", "uk-UA")];

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // crates/kb-core → repo root → data/wordlists
    let wordlists_dir = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("data").join("wordlists"))
        .expect("repo root not found");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR not set"));

    for (stem, tag) in LAYOUTS {
        let txt_path = wordlists_dir.join(format!("{stem}.txt"));
        let fst_path = out_dir.join(format!("{stem}.fst"));

        println!("cargo:rerun-if-changed={}", txt_path.display());

        let mut words: Vec<String> = match File::open(&txt_path) {
            Ok(f) => BufReader::new(f)
                .lines()
                .map_while(Result::ok)
                .map(|l| l.trim().to_lowercase())
                .filter(|l| !l.is_empty() && !l.starts_with('#'))
                .collect(),
            Err(e) => {
                println!(
                    "cargo:warning=wordlist for {tag} ({stem}) not found at {} — skipping ({e})",
                    txt_path.display()
                );
                Vec::new()
            }
        };
        words.sort();
        words.dedup();

        let writer =
            BufWriter::new(File::create(&fst_path).expect("could not create FST output file"));
        let mut builder = SetBuilder::new(writer).expect("FST set builder");
        for w in &words {
            builder.insert(w).expect("FST insert");
        }
        builder.finish().expect("FST finish");

        println!(
            "cargo:warning=wordlist {tag}: {} entries → {}",
            words.len(),
            fst_path.display()
        );
    }

    // Also write a small dispatcher so the lib code can map a stem to
    // its fst bytes via include_bytes! without hard-coding paths.
    let dispatch_path = out_dir.join("embedded_wordlists.rs");
    let mut dispatch = BufWriter::new(File::create(&dispatch_path).expect("dispatch file"));
    writeln!(
        &mut dispatch,
        "/// Generated by build.rs — embedded wordlist FST blobs."
    )
    .unwrap();
    writeln!(
        &mut dispatch,
        "pub const EMBEDDED_WORDLISTS: &[(&str, &[u8])] = &["
    )
    .unwrap();
    for (stem, _) in LAYOUTS {
        writeln!(
            &mut dispatch,
            "    (\"{stem}\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{stem}.fst\"))),"
        )
        .unwrap();
    }
    writeln!(&mut dispatch, "];").unwrap();
}
