//! Layout mappings — what each Win-SC1 scancode produces under each
//! supported layout. Loaded from `data/layout-mappings/*.toml` baked
//! into the binary at compile time.
//!
//! Adding a new layout = adding a TOML file there + listing it in
//! [`embedded_layouts`].

use std::collections::{HashMap, HashSet};
use std::path::Path;

use fst::Set as FstSet;
use kb_detect::{LayoutDictionary, LayoutProfile, Script};
use kb_types::{LayoutId, WordKey};
use serde::Deserialize;
use thiserror::Error;
use tracing::{info, warn};

// Generated by `build.rs` — declares EMBEDDED_WORDLISTS with
// `&[(stem, &'static [u8])]` containing FST blobs.
include!(concat!(env!("OUT_DIR"), "/embedded_wordlists.rs"));

#[derive(Debug, Error)]
pub enum LayoutLoadError {
    #[error("invalid layout TOML: {0}")]
    Toml(#[from] toml::de::Error),
}

/// Embedded layout descriptions baked into the binary at compile time.
/// `(stem, mapping TOML, FST file stem to look up in EMBEDDED_WORDLISTS)`
const fn embedded_layouts() -> &'static [(&'static str, &'static str, &'static str)] {
    &[
        (
            "en_us.toml",
            include_str!("../../../data/layout-mappings/en_us.toml"),
            "en_us",
        ),
        (
            "uk_ua.toml",
            include_str!("../../../data/layout-mappings/uk_ua.toml"),
            "uk_ua",
        ),
    ]
}

/// Look up the embedded FST blob for a given layout stem.
fn embedded_fst_for(stem: &str) -> Option<&'static [u8]> {
    EMBEDDED_WORDLISTS
        .iter()
        .find(|(s, _, _)| *s == stem)
        .map(|(_, bytes, _)| *bytes)
}

/// Look up the embedded short-stop-word list (raw text) for a given
/// layout stem.
fn embedded_stop_words_for(stem: &str) -> Option<&'static str> {
    EMBEDDED_WORDLISTS
        .iter()
        .find(|(s, _, _)| *s == stem)
        .map(|(_, _, txt)| *txt)
}

// ─── Raw TOML schema ─────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct LayoutToml {
    id: String,
    #[serde(default)]
    name: Option<String>,
    script: Script,
    keys: HashMap<String, KeyMapping>,
}

#[derive(Debug, Deserialize)]
struct KeyMapping {
    plain: String,
    #[serde(default)]
    shift: Option<String>,
}

// ─── In-memory representation ────────────────────────────────────────

#[derive(Clone)]
pub struct LayoutMapping {
    pub id: LayoutId,
    pub name: String,
    pub script: Script,
    /// scancode → (unshifted, shifted) characters.
    pub keys: HashMap<u32, (char, Option<char>)>,
    /// Pre-computed lower-case vowel set, for the detector profile.
    pub vowels: Vec<char>,
    /// Per-layout dictionary (compact FST + optional user-overlay).
    /// `None` means we have no dictionary for this layout — the
    /// detector falls through to plausibility-only.
    pub dictionary: Option<LayoutDictionary>,
}

impl std::fmt::Debug for LayoutMapping {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LayoutMapping")
            .field("id", &self.id)
            .field("name", &self.name)
            .field("script", &self.script)
            .field("keys_n", &self.keys.len())
            .field("dictionary_present", &self.dictionary.is_some())
            .finish()
    }
}

impl LayoutMapping {
    pub fn from_toml_str(input: &str) -> Result<Self, LayoutLoadError> {
        Self::from_parts(input, None)
    }

    /// Parse the layout TOML; bind an optional dictionary (FST blob +
    /// user overlay) to the resulting mapping.
    pub fn from_parts(
        toml_input: &str,
        dictionary: Option<LayoutDictionary>,
    ) -> Result<Self, LayoutLoadError> {
        let raw: LayoutToml = toml::from_str(toml_input)?;
        let id = LayoutId::new(raw.id);
        let name = raw.name.unwrap_or_else(|| id.as_str().to_owned());
        let script = raw.script;

        let mut keys = HashMap::with_capacity(raw.keys.len());
        for (k, v) in raw.keys {
            let Some(scancode) = parse_scancode(&k) else {
                warn!(key = %k, layout = %id, "ignoring unparseable scancode");
                continue;
            };
            let plain = first_char(&v.plain);
            let shift = v.shift.as_deref().and_then(first_char);
            if let Some(plain) = plain {
                keys.insert(scancode, (plain, shift));
            }
        }

        let vowels = derive_vowels(script);

        Ok(Self {
            id,
            name,
            script,
            keys,
            vowels,
            dictionary,
        })
    }

    /// Translate a single keystroke to the character produced under
    /// this layout, if known.
    pub fn translate_key(&self, key: WordKey) -> Option<char> {
        let (plain, shifted) = self.keys.get(&key.scancode)?;
        if key.shift {
            Some(shifted.unwrap_or(*plain))
        } else {
            Some(*plain)
        }
    }

    /// Translate an entire word buffer into a string under this layout.
    /// Untranslatable keystrokes are dropped silently.
    pub fn translate_buffer(&self, keys: &[WordKey]) -> String {
        let mut out = String::with_capacity(keys.len());
        for &k in keys {
            if let Some(c) = self.translate_key(k) {
                out.push(c);
            }
        }
        out
    }

    /// Build the [`LayoutProfile`] used by the detector pipeline.
    pub fn detector_profile(&self) -> LayoutProfile {
        LayoutProfile::new(self.id.clone(), self.script, self.vowels.iter().copied())
    }
}

fn parse_scancode(s: &str) -> Option<u32> {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
        u32::from_str_radix(rest, 16).ok()
    } else {
        s.parse::<u32>().ok()
    }
}

/// Parse a one-word-per-line text file into a lowercase HashSet.
/// Blank lines and `#` comments are skipped.
fn parse_wordlist(input: &str) -> HashSet<String> {
    input
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(str::to_lowercase)
        .collect()
}

/// Construct a [`LayoutDictionary`] for `stem`. The embedded FST
/// (the full upstream dictionary, used for ≥3-letter tokens) and the
/// embedded short-stop list (≤2-letter tokens) are baked at compile
/// time. On top of those, three runtime files in `<overlay_dir>` can
/// extend each layer without recompilation:
///
/// | User file                  | Merged into          | Use case                                                    |
/// |----------------------------|----------------------|-------------------------------------------------------------|
/// | `<stem>.txt`               | `user_overlay`       | "I want this word treated as a real word in this layout."   |
/// | `<stem>-extras.txt`        | `user_overlay`       | Same as above; separate file for the user to organise by    |
/// |                            |                      | category (mirrors the `data/wordlists/<stem>-extras.txt`    |
/// |                            |                      | source-tree convention).                                    |
/// | `<stem>-stop.txt`          | `short_stop_words`   | Curated 1- and 2-letter additions (mirrors the source-tree  |
/// |                            |                      | `<stem>-stop.txt`). Necessary because at ≤2 letters the     |
/// |                            |                      | embedded FST is intentionally bypassed.                     |
///
/// Why HashSet and not a runtime-built FST: user overlays in practice
/// stay under ~10 000 entries, where `HashSet` wins on lookup latency
/// (`O(1)` vs FST's `O(word_len)`) and is simpler to reason about.
/// FST shines only at hundreds of thousands of entries — that's why
/// it's the right pick for the embedded upstream dicts. We can bolt
/// on a runtime FST later if a user actually accumulates that many
/// custom words.
///
/// Missing files are silently fine. Read errors are logged and the
/// embedded data continues to work.
fn build_dictionary(stem: &str, overlay_dir: Option<&Path>) -> Option<LayoutDictionary> {
    let bytes = embedded_fst_for(stem)?;
    let embedded = match FstSet::new(bytes) {
        Ok(s) => s,
        Err(e) => {
            tracing::error!(stem, err = %e, "embedded FST is malformed; skipping dict for this layout");
            return None;
        }
    };

    // ── short-stop list: embedded baseline + optional user file ──
    let mut short_stop_words = embedded_stop_words_for(stem)
        .map(parse_wordlist)
        .unwrap_or_default();
    if let Some(extra) = load_overlay_file(overlay_dir, stem, "-stop") {
        short_stop_words.extend(extra);
    }

    // ── full overlay: <stem>.txt and <stem>-extras.txt merged ──
    let mut user_overlay: HashSet<String> = HashSet::new();
    if let Some(extra) = load_overlay_file(overlay_dir, stem, "") {
        user_overlay.extend(extra);
    }
    if let Some(extra) = load_overlay_file(overlay_dir, stem, "-extras") {
        user_overlay.extend(extra);
    }

    Some(LayoutDictionary::new(
        embedded,
        user_overlay,
        short_stop_words,
    ))
}

/// Read `<dir>/<stem><suffix>.txt` if present and parse it. Returns
/// `None` for both "no overlay dir configured" and "file does not
/// exist" — the caller treats both as "no user additions". Other I/O
/// errors are logged and treated the same way so a transient read
/// problem doesn't take the dict offline.
fn load_overlay_file(
    overlay_dir: Option<&Path>,
    stem: &str,
    suffix: &str,
) -> Option<HashSet<String>> {
    let dir = overlay_dir?;
    let path = dir.join(format!("{stem}{suffix}.txt"));
    match std::fs::read_to_string(&path) {
        Ok(s) => {
            let parsed = parse_wordlist(&s);
            info!(
                ?path,
                lines = s.lines().count(),
                words = parsed.len(),
                "merged user wordlist override"
            );
            Some(parsed)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => {
            warn!(?path, err = %e, "could not read user wordlist override");
            None
        }
    }
}

/// Path under which user-supplied wordlist overrides live:
/// `<config-dir>/kb-switcher/wordlists/`. Three optional files per
/// layout (see [`build_dictionary`] for the per-file semantics):
///
/// * `<stem>.txt` — runtime additions to the dictionary
/// * `<stem>-extras.txt` — same effect, separate file for organisation
/// * `<stem>-stop.txt` — runtime additions to the 1-/2-letter stop list
///
/// Reloading is wired through the engine's "Reload Settings" command,
/// so users can edit these without restarting the app.
pub fn user_wordlist_dir() -> Option<std::path::PathBuf> {
    crate::settings::SettingsStore::project_dirs()
        .ok()
        .map(|dirs| dirs.config_dir().join("wordlists"))
}

fn first_char(s: &str) -> Option<char> {
    s.chars().next()
}

/// Default vowel set per script — adjusted in code for languages whose
/// vowels diverge from the script default. Driven by the layout's `id`
/// so that uk-UA and ru-RU (both Cyrillic) get different sets.
fn derive_vowels(script: Script) -> Vec<char> {
    match script {
        Script::Latin => "aeiouy".chars().collect(),
        Script::Cyrillic => "аеиіоуюяєїыэ".chars().collect(),
        Script::Greek => "αεηιουω".chars().collect(),
        Script::Armenian => "աեէիոույ".chars().collect(),
        Script::Hebrew | Script::Arabic | Script::Other => Vec::new(),
    }
}

// ─── LayoutDb: handle to all loaded layouts ──────────────────────────

#[derive(Debug, Clone, Default)]
pub struct LayoutDb {
    by_id: HashMap<LayoutId, LayoutMapping>,
    /// Set of scancodes that map to an alphabetic character in *at
    /// least one* loaded layout. Used by [`WordBuffer`] to keep
    /// Cyrillic words intact when the user is typing them while the
    /// en-US layout is active (and vice-versa). Precomputed on load
    /// — cheap to query per-keystroke.
    letter_scancodes: HashSet<u32>,
}

impl LayoutDb {
    /// Load every layout embedded in the binary, bind its embedded
    /// FST dictionary, and merge any user-supplied wordlist override
    /// from `<config-dir>/wordlists/<stem>.txt`. Loud-but-graceful on
    /// parse errors — we log and continue so a single malformed
    /// dictionary can't take the whole app down.
    pub fn load_embedded() -> Self {
        Self::load_embedded_with_user_overlay(None)
    }

    /// Like [`load_embedded`] but lets the caller hand in the user
    /// override directory (so tests can isolate from the real
    /// filesystem). Production code uses `load_embedded`.
    pub fn load_embedded_with_user_overlay(overlay_dir: Option<&Path>) -> Self {
        let mut by_id = HashMap::new();
        for (name, body, fst_stem) in embedded_layouts() {
            let dictionary = build_dictionary(fst_stem, overlay_dir);
            match LayoutMapping::from_parts(body, dictionary) {
                Ok(layout) => {
                    info!(
                        layout = %layout.id,
                        keys = layout.keys.len(),
                        dict = layout.dictionary.is_some(),
                        "loaded embedded layout"
                    );
                    by_id.insert(layout.id.clone(), layout);
                }
                Err(e) => {
                    tracing::error!(file = name, err = %e, "failed to load embedded layout");
                }
            }
        }
        let letter_scancodes = compute_letter_scancodes(&by_id);
        Self {
            by_id,
            letter_scancodes,
        }
    }

    pub fn get(&self, id: &LayoutId) -> Option<&LayoutMapping> {
        self.by_id.get(id)
    }

    pub fn ids(&self) -> impl Iterator<Item = &LayoutId> {
        self.by_id.keys()
    }

    pub fn iter(&self) -> impl Iterator<Item = (&LayoutId, &LayoutMapping)> {
        self.by_id.iter()
    }

    pub fn len(&self) -> usize {
        self.by_id.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }

    /// Does this scancode map to an alphabetic character in *any* of
    /// the loaded layouts? The word buffer uses this to keep words
    /// intact when the user types in a script that the active OS
    /// layout treats as punctuation (Cyrillic letters under en-US,
    /// say). Layout-independent shifted variants count too — `є`
    /// lives at 0x28 even though en-US treats that key as `'`.
    pub fn is_letter_in_any_layout(&self, scancode: u32) -> bool {
        self.letter_scancodes.contains(&scancode)
    }
}

fn compute_letter_scancodes(by_id: &HashMap<LayoutId, LayoutMapping>) -> HashSet<u32> {
    let mut out = HashSet::new();
    for mapping in by_id.values() {
        for (&sc, (plain, shift)) in &mapping.keys {
            let plain_letter = plain.is_alphabetic();
            let shift_letter = shift.is_some_and(char::is_alphabetic);
            if plain_letter || shift_letter {
                out.insert(sc);
            }
        }
    }
    out
}

// ─── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_layouts_load() {
        let db = LayoutDb::load_embedded();
        assert!(db.get(&LayoutId::from("en-US")).is_some());
        assert!(db.get(&LayoutId::from("uk-UA")).is_some());
    }

    #[test]
    fn wordlists_loaded_with_layouts() {
        let db = LayoutDb::load_embedded();
        let en = db.get(&LayoutId::from("en-US")).expect("en-US");
        let uk = db.get(&LayoutId::from("uk-UA")).expect("uk-UA");
        // Sanity: dictionaries are present and contain core words +
        // single-letter prepositions / pronouns.
        let en_dict = en.dictionary.as_ref().expect("en dictionary");
        let uk_dict = uk.dictionary.as_ref().expect("uk dictionary");
        for w in ["the", "hello", "a", "i", "function", "world", "code"] {
            assert!(en_dict.contains(w), "en dict missing `{w}`");
        }
        // Common single-letter prepositions / pronouns / conjunctions
        // that the Hunspell dict actually ships (`ї` is intentionally
        // not in the list — it's a letter but never a standalone word).
        for w in [
            "що", "мені", "цим", "а", "і", "у", "о", "є", "я", "з", "в", "й",
        ] {
            assert!(uk_dict.contains(w), "uk dict missing `{w}`");
        }
        for w in ["слово", "привіт", "робити", "знати"] {
            assert!(uk_dict.contains(w), "uk dict missing `{w}`");
        }
    }

    #[test]
    fn round_trip_hello_through_uk() {
        let db = LayoutDb::load_embedded();
        let en = db.get(&LayoutId::from("en-US")).expect("en-US");
        let uk = db.get(&LayoutId::from("uk-UA")).expect("uk-UA");

        // Scancodes for h, e, l, l, o on a US-ANSI keyboard:
        let buf = vec![
            WordKey {
                scancode: 0x23,
                shift: false,
                timestamp_ms: 0,
            }, // h
            WordKey {
                scancode: 0x12,
                shift: false,
                timestamp_ms: 0,
            }, // e
            WordKey {
                scancode: 0x26,
                shift: false,
                timestamp_ms: 0,
            }, // l
            WordKey {
                scancode: 0x26,
                shift: false,
                timestamp_ms: 0,
            }, // l
            WordKey {
                scancode: 0x18,
                shift: false,
                timestamp_ms: 0,
            }, // o
        ];
        assert_eq!(en.translate_buffer(&buf), "hello");
        assert_eq!(uk.translate_buffer(&buf), "руддщ");
    }

    #[test]
    fn round_trip_pryvit_through_en() {
        let db = LayoutDb::load_embedded();
        let en = db.get(&LayoutId::from("en-US")).expect("en-US");
        let uk = db.get(&LayoutId::from("uk-UA")).expect("uk-UA");

        // Scancodes for п (0x22), р (0x23), и (0x30), в (0x20), і (0x1F), т (0x31)
        let buf = vec![
            WordKey {
                scancode: 0x22,
                shift: false,
                timestamp_ms: 0,
            },
            WordKey {
                scancode: 0x23,
                shift: false,
                timestamp_ms: 0,
            },
            WordKey {
                scancode: 0x30,
                shift: false,
                timestamp_ms: 0,
            },
            WordKey {
                scancode: 0x20,
                shift: false,
                timestamp_ms: 0,
            },
            WordKey {
                scancode: 0x1F,
                shift: false,
                timestamp_ms: 0,
            },
            WordKey {
                scancode: 0x31,
                shift: false,
                timestamp_ms: 0,
            },
        ];
        assert_eq!(uk.translate_buffer(&buf), "привіт");
        // The en-US rendering should be Latin-only too, even if not a word.
        let en_text = en.translate_buffer(&buf);
        assert!(en_text.is_ascii());
    }

    #[test]
    fn shift_picks_uppercase() {
        let db = LayoutDb::load_embedded();
        let en = db.get(&LayoutId::from("en-US")).expect("en-US");
        let buf = vec![WordKey {
            scancode: 0x23,
            shift: true,
            timestamp_ms: 0,
        }];
        assert_eq!(en.translate_buffer(&buf), "H");
    }

    // ─── User overlay loading (runtime-extensible) ───────────────────

    /// Tiny RAII tmpdir under `std::env::temp_dir()` — keeps these
    /// tests self-contained without dragging `tempfile` into deps.
    /// Builds on a per-test name + nanosecond timestamp + PID so two
    /// tests running in parallel can't clash.
    struct TmpDir(std::path::PathBuf);

    impl TmpDir {
        fn new(label: &str) -> Self {
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0);
            let path = std::env::temp_dir().join(format!(
                "kb-switcher-test-{label}-{}-{now}",
                std::process::id()
            ));
            std::fs::create_dir_all(&path).expect("mkdir tmp");
            Self(path)
        }

        fn write(&self, name: &str, body: &str) {
            std::fs::write(self.0.join(name), body).expect("write tmp file");
        }
    }

    impl Drop for TmpDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    /// `<stem>.txt` and `<stem>-extras.txt` are both merged into the
    /// runtime user overlay. Words from either file count as "real
    /// words" for any length, thanks to `LayoutDictionary::contains`
    /// consulting `user_overlay` first.
    #[test]
    fn user_overlay_picks_up_extras_file() {
        let tmp = TmpDir::new("extras");
        tmp.write("uk_ua.txt", "# user adds\nфайв\n");
        tmp.write("uk_ua-extras.txt", "# more\nекстраслово\n");

        let db = LayoutDb::load_embedded_with_user_overlay(Some(&tmp.0));
        let dict = db
            .get(&LayoutId::from("uk-UA"))
            .and_then(|l| l.dictionary.as_ref())
            .expect("uk dict");

        assert!(dict.contains("файв"), "<stem>.txt entry should be in dict");
        assert!(
            dict.contains("екстраслово"),
            "<stem>-extras.txt entry should be in dict"
        );
    }

    /// `<stem>-stop.txt` extends the curated short-stop list at
    /// runtime. This is the only path that affects ≤2-letter lookups
    /// (the embedded FST is intentionally bypassed there).
    #[test]
    fn user_short_stop_file_extends_stop_list() {
        let tmp = TmpDir::new("stop");
        // Two letter combo not in the embedded uk stop list.
        tmp.write("uk_ua-stop.txt", "хм\n");

        let db = LayoutDb::load_embedded_with_user_overlay(Some(&tmp.0));
        let dict = db
            .get(&LayoutId::from("uk-UA"))
            .and_then(|l| l.dictionary.as_ref())
            .expect("uk dict");

        assert!(
            dict.contains_short("хм"),
            "user-side -stop.txt should extend short stop list"
        );
    }

    /// Sanity: missing user files are silently fine — embedded data
    /// keeps working when the overlay dir is empty.
    #[test]
    fn missing_user_files_do_not_break_loading() {
        let tmp = TmpDir::new("empty");
        let db = LayoutDb::load_embedded_with_user_overlay(Some(&tmp.0));
        assert!(db.get(&LayoutId::from("en-US")).is_some());
        assert!(db.get(&LayoutId::from("uk-UA")).is_some());
    }

    /// Reload-style test: build twice with different overlay
    /// contents, confirming the second build sees the new data and
    /// the first build's data is fully replaced (not accumulated).
    /// Uses guaranteed-nonsense ASCII tokens because the embedded uk
    /// FST contains pretty much every real Cyrillic word — testing
    /// against real-language strings would always pass the positive
    /// half regardless of overlay state.
    #[test]
    fn overlay_is_freshly_read_on_each_build() {
        let tmp = TmpDir::new("reload");
        let first_token = "zxqzxqfirst";
        let second_token = "qwrqwrsecond";

        tmp.write("uk_ua.txt", &format!("{first_token}\n"));
        let first = LayoutDb::load_embedded_with_user_overlay(Some(&tmp.0));
        let first_dict = first
            .get(&LayoutId::from("uk-UA"))
            .and_then(|l| l.dictionary.as_ref())
            .expect("uk dict #1");
        assert!(first_dict.contains(first_token));
        assert!(!first_dict.contains(second_token));

        // User edits the file; engine reloads.
        tmp.write("uk_ua.txt", &format!("{second_token}\n"));
        let second = LayoutDb::load_embedded_with_user_overlay(Some(&tmp.0));
        let second_dict = second
            .get(&LayoutId::from("uk-UA"))
            .and_then(|l| l.dictionary.as_ref())
            .expect("uk dict #2");
        assert!(second_dict.contains(second_token));
        assert!(
            !second_dict.contains(first_token),
            "old overlay must not leak into the fresh load"
        );
    }
}
